os: linux
dist: bionic
language: python
python:
  - "2.7"
services:
  - docker
install:
  - pip install pycodestyle
  - pip install pylint
script:
  - pycodestyle --max-line-length=120 --show-source --show-pep8 run.py
  - pylint run.py
  - ./test/travis-test.sh
